### ISSUE TITLE
Request for new DataTables 1.10.10

### ISSUE THREAD

**Issue by ganov** [webjars/datatables#14]
Hi James,

First of all, i'd like to send you an 'extra thanks' for your DataTables Webjar wich helps me so much !! 

I'm also sure that you know DataTables is now on its V1.10.10. (https://cdn.datatables.net/)
I'd like to know if you plan to provide this new version ? 

Again, Thank's for your work.

Ganov

**Comment by jamesward** [comment]
Fixed by #15
