### ISSUE TITLE
bootstrap integration in v1.10.10

### ISSUE THREAD

**Issue by gseifert** [webjars/datatables#16]
The datatables bootstrap integration is now in the core library.  The webjars datatables v1.10.10 jar file doesn't seem to include the dataTables.bootstrap.css file, it only has the bootstrap javascript files.  Is it because the pom file filters for "css/jquery*" and so dataTables.bootstrap.css is not included since it doesn't start with "jquery"?

**Comment by jamesward** [comment]
I'm seeing that file:
http://www.webjars.org/listfiles/org.webjars.bower/datatables/1.10.10

Are you seeing something different?

**Comment by gseifert** [comment]
i'm using webjars classic (http://www.webjars.org/listfiles/datatables/1.10.10) which doesn't seem to have it?

**Comment by jamesward** [comment]
Oh whoops.  I'll get a fix asap.

**Comment by gseifert** [comment]
thanks for the quick fix!  do i need to wait a certain amount of time then before this update will be available?

**Comment by jamesward** [comment]
Sometimes the Maven Central sync takes a bit.  But it should be there around now.
