### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by fracoon** [webjars/datatables#18]
can we please include css requirejs config? like in bootstrap:
requirejs.config({
  paths: { 
    "bootstrap": webjars.path("bootstrap", "js/bootstrap"),
    "bootstrap-css": webjars.path("bootstrap", "css/bootstrap")  
  },
  shim: { "bootstrap": [ "jquery" ] }
});

**Comment by jamesward** [comment]
Recent versions of `webjars-locator` use the config from the `pom.xml` file which is currently:
```
            {
                "paths": { "datatables": "js/jquery.dataTables" },
                "shim": { "datatables": [ "jquery" ] }
            }
```

That should be working as expected.
